name: kf_ess_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+4

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state mangament
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  provider: ^6.1.2

  # security
  encrypt: ^5.0.3
  flutter_dotenv: ^5.2.1
  pointycastle: ^4.0.0
  local_auth: ^2.3.0
  
  # tools
  file_picker: ^10.1.2
  url_launcher: ^6.3.0
  share_plus: ^11.0.0
  path_provider: ^2.1.4
  flutter_pdfview: ^1.4.0+1
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  device_info_plus: #^11.4.0


  # network
  dio: ^5.8.0+1
  talker_dio_logger: ^4.7.2
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  connectivity_plus: ^6.1.4
  http: ^1.3.0
 
  


  # ui &
  auto_size_text: ^3.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.7.0
  carousel_slider_plus: ^7.0.1
  infinite_scroll_pagination: ^5.0.0
  toggle_switch: ^2.3.0
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_easyloading: ^3.0.5
  timeline_tile_plus: ^0.0.3
  table_calendar: ^3.2.0
  date_picker_plus: ^4.2.0

  awesome_snackbar_content:
    git:
      url: https://github.com/AbdelrahmanMahmoudM94/awesome_snackbar_content
      ref: main

  # injectable
  injectable: ^2.5.0
  get_it: ^8.0.0

  # localization
  easy_localization: ^3.0.7

  # navigation
  auto_route: ^10.0.1

  # google map & location
  google_maps_flutter: ^2.9.0

  # serialization
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0

  flutter_native_splash: ^2.4.1

  # form builder
  flutter_form_builder: #^10.0.1
  form_builder_validators: ^11.0.0

  dropdown_button2: ^2.3.9
  # storage
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4

  # other
  dartz: ^0.10.1
  logger: ^2.4.0

  # webview
  webview_flutter: ^4.11.0

  # localization
  intl: ^0.20.0


  # hardwere
  flutter_keyboard_visibility: ^6.0.0

  # firebase services
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  firebase_crashlytics: ^4.3.1
  flutter_local_notifications: ^19.1.0


dev_dependencies:

  remove_unused_localizations_keys: ^0.0.40
  freezed: any
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  flutter_lints: ^5.0.0
  translations_cleaner: ^0.0.5

dependency_overrides:
  intl: ^0.20.0
  pointycastle: ^4.0.0
  flutter_gen_core:
    git:
      url: https://github.com/FlutterGen/flutter_gen.git
      path: packages/core/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  line_length: 80 # Optional (default: 80)
  # Optional
  integrations:
    flutter_svg: true
    rive: false
    lottie: false

  assets:
    enabled: true
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
    - assets/pdf/
    - assets/svg/
    - assets/png/
    - assets/translations/
    - assets/public/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
